// flow-typed signature: 224923f070e73e1d5cf09f5b3c1786a3
// flow-typed version: <<STUB>>/babel-plugin-wrap-in-js_v^1.1.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-wrap-in-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-wrap-in-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-wrap-in-js/index' {
  declare module.exports: $Exports<'babel-plugin-wrap-in-js'>;
}
declare module 'babel-plugin-wrap-in-js/index.js' {
  declare module.exports: $Exports<'babel-plugin-wrap-in-js'>;
}
