// flow-typed signature: 303d9643a7e910fdc265c4d990993300
// flow-typed version: <<STUB>>/fetch-github-organization_v^1.0.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-github-organization'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-github-organization' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fetch-github-organization/index' {
  declare module.exports: $Exports<'fetch-github-organization'>;
}
declare module 'fetch-github-organization/index.js' {
  declare module.exports: $Exports<'fetch-github-organization'>;
}
