// flow-typed signature: f72684b11f063ca8fc59ec6f5a460ad9
// flow-typed version: <<STUB>>/in-view_v^0.6.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'in-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'in-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'in-view/dist/in-view.min' {
  declare module.exports: any;
}

declare module 'in-view/docs/docs.webpack.config' {
  declare module.exports: any;
}

declare module 'in-view/docs/lib/js/bundle.min' {
  declare module.exports: any;
}

declare module 'in-view/docs/lib/js/main' {
  declare module.exports: any;
}

declare module 'in-view/src/in-view' {
  declare module.exports: any;
}

declare module 'in-view/src/index' {
  declare module.exports: any;
}

declare module 'in-view/src/registry' {
  declare module.exports: any;
}

declare module 'in-view/src/viewport' {
  declare module.exports: any;
}

declare module 'in-view/test/helpers/setup-browser-env' {
  declare module.exports: any;
}

declare module 'in-view/test/in-view.is.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/in-view.offset.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/in-view.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/in-view.test.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/inview.threshold.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/registry.check.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/registry.emit.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/registry.on.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/registry.once.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/registry.spec' {
  declare module.exports: any;
}

declare module 'in-view/test/viewport.spec' {
  declare module.exports: any;
}

declare module 'in-view/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'in-view/dist/in-view.min.js' {
  declare module.exports: $Exports<'in-view/dist/in-view.min'>;
}
declare module 'in-view/docs/docs.webpack.config.js' {
  declare module.exports: $Exports<'in-view/docs/docs.webpack.config'>;
}
declare module 'in-view/docs/lib/js/bundle.min.js' {
  declare module.exports: $Exports<'in-view/docs/lib/js/bundle.min'>;
}
declare module 'in-view/docs/lib/js/main.js' {
  declare module.exports: $Exports<'in-view/docs/lib/js/main'>;
}
declare module 'in-view/src/in-view.js' {
  declare module.exports: $Exports<'in-view/src/in-view'>;
}
declare module 'in-view/src/index.js' {
  declare module.exports: $Exports<'in-view/src/index'>;
}
declare module 'in-view/src/registry.js' {
  declare module.exports: $Exports<'in-view/src/registry'>;
}
declare module 'in-view/src/viewport.js' {
  declare module.exports: $Exports<'in-view/src/viewport'>;
}
declare module 'in-view/test/helpers/setup-browser-env.js' {
  declare module.exports: $Exports<'in-view/test/helpers/setup-browser-env'>;
}
declare module 'in-view/test/in-view.is.spec.js' {
  declare module.exports: $Exports<'in-view/test/in-view.is.spec'>;
}
declare module 'in-view/test/in-view.offset.spec.js' {
  declare module.exports: $Exports<'in-view/test/in-view.offset.spec'>;
}
declare module 'in-view/test/in-view.spec.js' {
  declare module.exports: $Exports<'in-view/test/in-view.spec'>;
}
declare module 'in-view/test/in-view.test.spec.js' {
  declare module.exports: $Exports<'in-view/test/in-view.test.spec'>;
}
declare module 'in-view/test/inview.threshold.spec.js' {
  declare module.exports: $Exports<'in-view/test/inview.threshold.spec'>;
}
declare module 'in-view/test/registry.check.spec.js' {
  declare module.exports: $Exports<'in-view/test/registry.check.spec'>;
}
declare module 'in-view/test/registry.emit.spec.js' {
  declare module.exports: $Exports<'in-view/test/registry.emit.spec'>;
}
declare module 'in-view/test/registry.on.spec.js' {
  declare module.exports: $Exports<'in-view/test/registry.on.spec'>;
}
declare module 'in-view/test/registry.once.spec.js' {
  declare module.exports: $Exports<'in-view/test/registry.once.spec'>;
}
declare module 'in-view/test/registry.spec.js' {
  declare module.exports: $Exports<'in-view/test/registry.spec'>;
}
declare module 'in-view/test/viewport.spec.js' {
  declare module.exports: $Exports<'in-view/test/viewport.spec'>;
}
declare module 'in-view/webpack.config.js' {
  declare module.exports: $Exports<'in-view/webpack.config'>;
}
