// flow-typed signature: 7268f1c9df13cf78ecf001b7be07b089
// flow-typed version: <<STUB>>/mdi_v^2.2.43/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mdi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mdi' {
  declare module.exports: any;
}
