// flow-typed signature: 76e583d88923a492732089ddb0a0b1cc
// flow-typed version: <<STUB>>/nteract-members_v^1.0.8/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nteract-members'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nteract-members' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'nteract-members/index' {
  declare module.exports: $Exports<'nteract-members'>;
}
declare module 'nteract-members/index.js' {
  declare module.exports: $Exports<'nteract-members'>;
}
