// flow-typed signature: b9cbe3024825df958d680d7869d78a0f
// flow-typed version: <<STUB>>/postcss-easy-import_v^3.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-easy-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-easy-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-easy-import/lib/add-prefix' {
  declare module.exports: any;
}

declare module 'postcss-easy-import/lib/has-extensions' {
  declare module.exports: any;
}

declare module 'postcss-easy-import/lib/has-prefix' {
  declare module.exports: any;
}

declare module 'postcss-easy-import/lib/resolve-glob' {
  declare module.exports: any;
}

declare module 'postcss-easy-import/lib/resolve-module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-easy-import/index' {
  declare module.exports: $Exports<'postcss-easy-import'>;
}
declare module 'postcss-easy-import/index.js' {
  declare module.exports: $Exports<'postcss-easy-import'>;
}
declare module 'postcss-easy-import/lib/add-prefix.js' {
  declare module.exports: $Exports<'postcss-easy-import/lib/add-prefix'>;
}
declare module 'postcss-easy-import/lib/has-extensions.js' {
  declare module.exports: $Exports<'postcss-easy-import/lib/has-extensions'>;
}
declare module 'postcss-easy-import/lib/has-prefix.js' {
  declare module.exports: $Exports<'postcss-easy-import/lib/has-prefix'>;
}
declare module 'postcss-easy-import/lib/resolve-glob.js' {
  declare module.exports: $Exports<'postcss-easy-import/lib/resolve-glob'>;
}
declare module 'postcss-easy-import/lib/resolve-module.js' {
  declare module.exports: $Exports<'postcss-easy-import/lib/resolve-module'>;
}
