// flow-typed signature: 8789f5b899d448bdca3d639550ed14c9
// flow-typed version: <<STUB>>/react-headroom_v^2.2.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-headroom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-headroom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-headroom/dist/index' {
  declare module.exports: any;
}

declare module 'react-headroom/dist/shouldUpdate' {
  declare module.exports: any;
}

declare module 'react-headroom/src/index' {
  declare module.exports: any;
}

declare module 'react-headroom/src/shouldUpdate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-headroom/dist/index.js' {
  declare module.exports: $Exports<'react-headroom/dist/index'>;
}
declare module 'react-headroom/dist/shouldUpdate.js' {
  declare module.exports: $Exports<'react-headroom/dist/shouldUpdate'>;
}
declare module 'react-headroom/src/index.js' {
  declare module.exports: $Exports<'react-headroom/src/index'>;
}
declare module 'react-headroom/src/shouldUpdate.js' {
  declare module.exports: $Exports<'react-headroom/src/shouldUpdate'>;
}
