// flow-typed signature: 4480b55f5f1e4a76cfe98313de7eb2a8
// flow-typed version: <<STUB>>/react-spring_v^5.1.7/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spring/dist/addons.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/dist/addons.es' {
  declare module.exports: any;
}

declare module 'react-spring/dist/addons.umd' {
  declare module.exports: any;
}

declare module 'react-spring/dist/react-spring.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/dist/react-spring.es' {
  declare module.exports: any;
}

declare module 'react-spring/dist/react-spring.umd' {
  declare module.exports: any;
}

declare module 'react-spring/src/addons/Easing' {
  declare module.exports: any;
}

declare module 'react-spring/src/addons/index' {
  declare module.exports: any;
}

declare module 'react-spring/src/addons/OscillatorAnimation' {
  declare module.exports: any;
}

declare module 'react-spring/src/addons/TimingAnimation' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/Animated' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/AnimatedArray' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/AnimatedController' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/AnimatedInterpolation' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/AnimatedStyle' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/AnimatedTracking' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/AnimatedValue' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/AnimatedWithChildren' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/Animation' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/Globals' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/SpringAnimation' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/targets/Interpolation' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/targets/react-dom/fix-auto' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/targets/react-dom/index' {
  declare module.exports: any;
}

declare module 'react-spring/src/animated/targets/react-native/index' {
  declare module.exports: any;
}

declare module 'react-spring/src/index' {
  declare module.exports: any;
}

declare module 'react-spring/src/Keyframes' {
  declare module.exports: any;
}

declare module 'react-spring/src/normalize-css-color/index' {
  declare module.exports: any;
}

declare module 'react-spring/src/Parallax' {
  declare module.exports: any;
}

declare module 'react-spring/src/Spring' {
  declare module.exports: any;
}

declare module 'react-spring/src/Trail' {
  declare module.exports: any;
}

declare module 'react-spring/src/Transition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spring/dist/addons.cjs.js' {
  declare module.exports: $Exports<'react-spring/dist/addons.cjs'>;
}
declare module 'react-spring/dist/addons.es.js' {
  declare module.exports: $Exports<'react-spring/dist/addons.es'>;
}
declare module 'react-spring/dist/addons.umd.js' {
  declare module.exports: $Exports<'react-spring/dist/addons.umd'>;
}
declare module 'react-spring/dist/react-spring.cjs.js' {
  declare module.exports: $Exports<'react-spring/dist/react-spring.cjs'>;
}
declare module 'react-spring/dist/react-spring.es.js' {
  declare module.exports: $Exports<'react-spring/dist/react-spring.es'>;
}
declare module 'react-spring/dist/react-spring.umd.js' {
  declare module.exports: $Exports<'react-spring/dist/react-spring.umd'>;
}
declare module 'react-spring/src/addons/Easing.js' {
  declare module.exports: $Exports<'react-spring/src/addons/Easing'>;
}
declare module 'react-spring/src/addons/index.js' {
  declare module.exports: $Exports<'react-spring/src/addons/index'>;
}
declare module 'react-spring/src/addons/OscillatorAnimation.js' {
  declare module.exports: $Exports<'react-spring/src/addons/OscillatorAnimation'>;
}
declare module 'react-spring/src/addons/TimingAnimation.js' {
  declare module.exports: $Exports<'react-spring/src/addons/TimingAnimation'>;
}
declare module 'react-spring/src/animated/Animated.js' {
  declare module.exports: $Exports<'react-spring/src/animated/Animated'>;
}
declare module 'react-spring/src/animated/AnimatedArray.js' {
  declare module.exports: $Exports<'react-spring/src/animated/AnimatedArray'>;
}
declare module 'react-spring/src/animated/AnimatedController.js' {
  declare module.exports: $Exports<'react-spring/src/animated/AnimatedController'>;
}
declare module 'react-spring/src/animated/AnimatedInterpolation.js' {
  declare module.exports: $Exports<'react-spring/src/animated/AnimatedInterpolation'>;
}
declare module 'react-spring/src/animated/AnimatedProps.js' {
  declare module.exports: $Exports<'react-spring/src/animated/AnimatedProps'>;
}
declare module 'react-spring/src/animated/AnimatedStyle.js' {
  declare module.exports: $Exports<'react-spring/src/animated/AnimatedStyle'>;
}
declare module 'react-spring/src/animated/AnimatedTracking.js' {
  declare module.exports: $Exports<'react-spring/src/animated/AnimatedTracking'>;
}
declare module 'react-spring/src/animated/AnimatedValue.js' {
  declare module.exports: $Exports<'react-spring/src/animated/AnimatedValue'>;
}
declare module 'react-spring/src/animated/AnimatedWithChildren.js' {
  declare module.exports: $Exports<'react-spring/src/animated/AnimatedWithChildren'>;
}
declare module 'react-spring/src/animated/Animation.js' {
  declare module.exports: $Exports<'react-spring/src/animated/Animation'>;
}
declare module 'react-spring/src/animated/createAnimatedComponent.js' {
  declare module.exports: $Exports<'react-spring/src/animated/createAnimatedComponent'>;
}
declare module 'react-spring/src/animated/Globals.js' {
  declare module.exports: $Exports<'react-spring/src/animated/Globals'>;
}
declare module 'react-spring/src/animated/SpringAnimation.js' {
  declare module.exports: $Exports<'react-spring/src/animated/SpringAnimation'>;
}
declare module 'react-spring/src/animated/targets/Interpolation.js' {
  declare module.exports: $Exports<'react-spring/src/animated/targets/Interpolation'>;
}
declare module 'react-spring/src/animated/targets/react-dom/fix-auto.js' {
  declare module.exports: $Exports<'react-spring/src/animated/targets/react-dom/fix-auto'>;
}
declare module 'react-spring/src/animated/targets/react-dom/index.js' {
  declare module.exports: $Exports<'react-spring/src/animated/targets/react-dom/index'>;
}
declare module 'react-spring/src/animated/targets/react-native/index.js' {
  declare module.exports: $Exports<'react-spring/src/animated/targets/react-native/index'>;
}
declare module 'react-spring/src/index.js' {
  declare module.exports: $Exports<'react-spring/src/index'>;
}
declare module 'react-spring/src/Keyframes.js' {
  declare module.exports: $Exports<'react-spring/src/Keyframes'>;
}
declare module 'react-spring/src/normalize-css-color/index.js' {
  declare module.exports: $Exports<'react-spring/src/normalize-css-color/index'>;
}
declare module 'react-spring/src/Parallax.js' {
  declare module.exports: $Exports<'react-spring/src/Parallax'>;
}
declare module 'react-spring/src/Spring.js' {
  declare module.exports: $Exports<'react-spring/src/Spring'>;
}
declare module 'react-spring/src/Trail.js' {
  declare module.exports: $Exports<'react-spring/src/Trail'>;
}
declare module 'react-spring/src/Transition.js' {
  declare module.exports: $Exports<'react-spring/src/Transition'>;
}
