// flow-typed signature: 4b9e23232a068a478335494a1ae1ae57
// flow-typed version: <<STUB>>/react-fns_v^1.4.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fns' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fns/dist/index.es6' {
  declare module.exports: any;
}

declare module 'react-fns/dist/index' {
  declare module.exports: any;
}

declare module 'react-fns/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-fns/dist/index.umd.min' {
  declare module.exports: any;
}

declare module 'react-fns/rollup.config' {
  declare module.exports: any;
}

declare module 'react-fns/website/core/Footer' {
  declare module.exports: any;
}

declare module 'react-fns/website/deploy' {
  declare module.exports: any;
}

declare module 'react-fns/website/languages' {
  declare module.exports: any;
}

declare module 'react-fns/website/pages/en/help-with-translations' {
  declare module.exports: any;
}

declare module 'react-fns/website/pages/en/index' {
  declare module.exports: any;
}

declare module 'react-fns/website/siteConfig' {
  declare module.exports: any;
}

declare module 'react-fns/website/static/js/pjax-api' {
  declare module.exports: any;
}

declare module 'react-fns/website/static/js/redirect' {
  declare module.exports: any;
}

declare module 'react-fns/website/static/js/redirectBlog' {
  declare module.exports: any;
}

declare module 'react-fns/website/static/js/redirectIndex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fns/dist/index.es6.js' {
  declare module.exports: $Exports<'react-fns/dist/index.es6'>;
}
declare module 'react-fns/dist/index.js' {
  declare module.exports: $Exports<'react-fns/dist/index'>;
}
declare module 'react-fns/dist/index.umd.js' {
  declare module.exports: $Exports<'react-fns/dist/index.umd'>;
}
declare module 'react-fns/dist/index.umd.min.js' {
  declare module.exports: $Exports<'react-fns/dist/index.umd.min'>;
}
declare module 'react-fns/rollup.config.js' {
  declare module.exports: $Exports<'react-fns/rollup.config'>;
}
declare module 'react-fns/website/core/Footer.js' {
  declare module.exports: $Exports<'react-fns/website/core/Footer'>;
}
declare module 'react-fns/website/deploy.js' {
  declare module.exports: $Exports<'react-fns/website/deploy'>;
}
declare module 'react-fns/website/languages.js' {
  declare module.exports: $Exports<'react-fns/website/languages'>;
}
declare module 'react-fns/website/pages/en/help-with-translations.js' {
  declare module.exports: $Exports<'react-fns/website/pages/en/help-with-translations'>;
}
declare module 'react-fns/website/pages/en/index.js' {
  declare module.exports: $Exports<'react-fns/website/pages/en/index'>;
}
declare module 'react-fns/website/siteConfig.js' {
  declare module.exports: $Exports<'react-fns/website/siteConfig'>;
}
declare module 'react-fns/website/static/js/pjax-api.js' {
  declare module.exports: $Exports<'react-fns/website/static/js/pjax-api'>;
}
declare module 'react-fns/website/static/js/redirect.js' {
  declare module.exports: $Exports<'react-fns/website/static/js/redirect'>;
}
declare module 'react-fns/website/static/js/redirectBlog.js' {
  declare module.exports: $Exports<'react-fns/website/static/js/redirectBlog'>;
}
declare module 'react-fns/website/static/js/redirectIndex.js' {
  declare module.exports: $Exports<'react-fns/website/static/js/redirectIndex'>;
}
