// flow-typed signature: 7a1a32a59c5340459e5d27704552ff75
// flow-typed version: <<STUB>>/styled-system_v^2.2.5/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-system/dist/constants' {
  declare module.exports: any;
}

declare module 'styled-system/dist/index' {
  declare module.exports: any;
}

declare module 'styled-system/dist/space' {
  declare module.exports: any;
}

declare module 'styled-system/dist/styles' {
  declare module.exports: any;
}

declare module 'styled-system/dist/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-system/dist/constants.js' {
  declare module.exports: $Exports<'styled-system/dist/constants'>;
}
declare module 'styled-system/dist/index.js' {
  declare module.exports: $Exports<'styled-system/dist/index'>;
}
declare module 'styled-system/dist/space.js' {
  declare module.exports: $Exports<'styled-system/dist/space'>;
}
declare module 'styled-system/dist/styles.js' {
  declare module.exports: $Exports<'styled-system/dist/styles'>;
}
declare module 'styled-system/dist/util.js' {
  declare module.exports: $Exports<'styled-system/dist/util'>;
}
