name: Build and validate
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: yarn
      - run: NODE_OPTIONS=--openssl-legacy-provider yarn build
      - run: yarn flow